#!/usr/bin/env python3
"""Generate a testing gaps report from coverage.json.

This script reads the coverage report generated by pytest-cov and produces
a markdown report of current coverage status. The output replaces
tests/TESTING_GAPS.md with an up-to-date snapshot.

Usage:
    pytest --cov --cov-report=json
    python scripts/generate_gaps_report.py

Output:
    Writes directly to tests/TESTING_GAPS.md (or prints to stdout if --stdout).
"""

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

SOURCE_PREFIX = "src/powerpetdoor/"


def _collect_pragma_exclusions(source_dir: Path) -> dict[str, list[dict]]:
    """Scan source files for pragma annotations and collect them.

    Returns a dict mapping relative file paths to lists of pragma entries,
    each with 'line', 'end_line', 'pragma_type', 'reason', and 'code'.
    """
    pragma_re = re.compile(
        r"#\s*pragma:\s*no\s+(cover|branch)"
        r"(?:\s*\(([^)]+)\))?",  # optional reason in parens
    )
    exclusions: dict[str, list[dict]] = {}

    for py_file in sorted(source_dir.rglob("*.py")):
        rel_path = str(py_file.relative_to(source_dir.parent.parent))
        # Skip __init__.py and __main__.py (excluded from coverage entirely)
        if py_file.name in ("__init__.py", "__main__.py"):
            continue

        try:
            file_lines = py_file.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeDecodeError):
            continue

        # Track last pragma for grouping consecutive lines of the same type
        last_line_num = 0
        last_pragma_type = ""

        for i, line in enumerate(file_lines, start=1):
            match = pragma_re.search(line)
            if not match:
                continue

            pragma_type = match.group(1)  # "cover" or "branch"
            reason = (match.group(2) or "").strip()

            # Group consecutive lines with the same pragma type
            if (
                rel_path in exclusions
                and exclusions[rel_path]
                and i == last_line_num + 1
                and pragma_type == last_pragma_type
            ):
                # Extend the existing range
                entry = exclusions[rel_path][-1]
                entry["end_line"] = i
                # Inherit reason from first line if this line has none
                if reason and not entry["reason"]:
                    entry["reason"] = reason
                last_line_num = i
                continue

            last_line_num = i
            last_pragma_type = pragma_type

            code = line.strip()
            # Remove the pragma comment itself for cleaner display
            code_before_pragma = code[: code.index("# pragma:")].rstrip()

            entry = {
                "line": i,
                "end_line": i,
                "pragma_type": pragma_type,
                "reason": reason,
                "code": code_before_pragma if code_before_pragma else code,
            }
            exclusions.setdefault(rel_path, []).append(entry)

    return exclusions


def _group_lines(lines: list[int]) -> str:
    """Group consecutive line numbers into ranges for readability."""
    if not lines:
        return ""
    ranges = []
    start = end = lines[0]
    for line in lines[1:]:
        if line == end + 1:
            end = line
        else:
            ranges.append(str(start) if start == end else f"{start}-{end}")
            start = end = line
    ranges.append(str(start) if start == end else f"{start}-{end}")
    return ", ".join(ranges)


def _categorize(path: str) -> str:
    """Categorize a source file path into a logical group."""
    p = path.replace(SOURCE_PREFIX, "")

    if p.startswith("simulator/commands/"):
        return "Simulator Commands"
    if p in ("simulator/cli.py", "simulator/ctl.py", "simulator/prompt_common.py"):
        return "Simulator CLI"
    if p.startswith("simulator/"):
        return "Simulator"
    return "Core Library"


def main() -> int:
    """Generate and output the testing gaps report."""
    coverage_file = Path("coverage.json")
    stdout_mode = "--stdout" in sys.argv

    if not coverage_file.exists():
        msg = (
            "# Testing Gaps Report\n\n"
            "**Error**: No `coverage.json` found.\n\n"
            "Run `pytest --cov --cov-report=json` first to generate coverage data.\n"
        )
        if stdout_mode:
            print(msg)
        else:
            Path("tests/TESTING_GAPS.md").write_text(msg)
        return 1

    with open(coverage_file) as f:
        data = json.load(f)

    totals = data.get("totals", {})
    percent_covered = totals.get("percent_covered", 0)
    covered_lines = totals.get("covered_lines", 0)
    missing_lines = totals.get("missing_lines", 0)
    total_lines = covered_lines + missing_lines
    covered_branches = totals.get("covered_branches", 0)
    missing_branches = totals.get("missing_branches", 0)
    total_branches = covered_branches + missing_branches
    branch_pct = (covered_branches / total_branches * 100) if total_branches else 100.0

    lines = []
    lines.append("# Testing Gaps Report")
    lines.append("")
    lines.append("This file is **auto-generated** by CI after each test run. Do not edit manually.")
    lines.append("")
    lines.append(f"**Last updated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Line Coverage | {percent_covered:.2f}% |")
    lines.append(f"| Branch Coverage | {branch_pct:.2f}% |")
    lines.append(f"| Lines Covered | {covered_lines:,} / {total_lines:,} |")
    lines.append(f"| Branches Covered | {covered_branches:,} / {total_branches:,} |")
    lines.append(f"| Lines Missing | {missing_lines:,} |")
    lines.append("")

    # Collect all files and categorize
    all_files = []
    files_with_gaps = []
    for filepath, file_data in data.get("files", {}).items():
        summary = file_data.get("summary", {})
        file_percent = summary.get("percent_covered", 100)
        stmts = summary.get("num_statements", 0)
        num_branches = summary.get("num_branches", 0)
        file_info = {
            "path": filepath.replace(SOURCE_PREFIX, ""),
            "full_path": filepath,
            "percent": file_percent,
            "stmts": stmts,
            "branches": num_branches,
            "covered": summary.get("covered_lines", 0),
            "missing": summary.get("missing_lines", 0),
            "missing_line_numbers": file_data.get("missing_lines", []),
            "missing_branch_numbers": file_data.get("missing_branches", []),
            "category": _categorize(filepath),
        }
        all_files.append(file_info)
        if file_percent < 100:
            files_with_gaps.append(file_info)

    # Group by category for summary
    categories: dict[str, list] = {}
    for f in all_files:
        categories.setdefault(f["category"], []).append(f)

    # Category summary
    lines.append("## Coverage by Category")
    lines.append("")
    lines.append("| Category | Files | Coverage | Status |")
    lines.append("|----------|-------|----------|--------|")

    for cat_name in sorted(categories.keys()):
        cat_files = categories[cat_name]
        cat_stmts = sum(f["stmts"] for f in cat_files)
        cat_covered = sum(f["covered"] for f in cat_files)
        cat_pct = (cat_covered / cat_stmts * 100) if cat_stmts else 100.0
        cat_gaps = sum(1 for f in cat_files if f["percent"] < 100)
        status = ":green_circle:" if cat_pct >= 99.5 else ":yellow_circle:"
        gap_note = f" ({cat_gaps} with gaps)" if cat_gaps else ""
        lines.append(f"| {cat_name} | {len(cat_files)}{gap_note} | {cat_pct:.1f}% | {status} |")

    lines.append("")

    if not files_with_gaps:
        lines.append("## Status: 100% Coverage :green_circle:")
        lines.append("")
        lines.append("All code is covered by tests. No gaps to report.")
        lines.append("")
    else:
        files_with_gaps.sort(key=lambda x: x["percent"])

        lines.append(f"## Current Gaps ({len(files_with_gaps)} files)")
        lines.append("")
        lines.append("| Module | Stmts | Missing | Coverage |")
        lines.append("|--------|-------|---------|----------|")

        for fi in files_with_gaps:
            lines.append(
                f"| `{fi['path']}` | {fi['stmts']} | {fi['missing']} | {fi['percent']:.1f}% |"
            )

        lines.append("")
        lines.append("### Missing Lines Detail")
        lines.append("")

        for fi in files_with_gaps:
            if fi["missing_line_numbers"]:
                lines.append(f"**`{fi['path']}`**: {_group_lines(fi['missing_line_numbers'])}")
                lines.append("")

    # Collect pragma exclusions from source files
    source_dir = Path("src/powerpetdoor")
    pragma_exclusions = _collect_pragma_exclusions(source_dir) if source_dir.exists() else {}

    # Pragma exclusions section
    lines.append("## Coverage Exclusions")
    lines.append("")
    lines.append("### Automatic Exclusions")
    lines.append("")
    lines.append("The following are excluded from coverage by configuration (`pyproject.toml`):")
    lines.append("")
    lines.append("- `*/__init__.py` - Package init files")
    lines.append("- `*/__main__.py` - Entry point files")
    lines.append("- `def __repr__` - String representation methods")
    lines.append("- `raise NotImplementedError` - Abstract method stubs")
    lines.append("- `if TYPE_CHECKING:` - Type-checking-only imports")
    lines.append("- `@overload` - Typing overload declarations")
    lines.append("")

    if pragma_exclusions:
        total_pragma_lines = 0
        total_pragma_entries = 0
        for entries in pragma_exclusions.values():
            total_pragma_entries += len(entries)
            for e in entries:
                total_pragma_lines += e["end_line"] - e["line"] + 1

        lines.append("### Pragma Exclusions")
        lines.append("")
        lines.append(
            f"**{total_pragma_lines} lines** across **{len(pragma_exclusions)} files** "
            f"are excluded via `# pragma: no cover` or `# pragma: no branch`."
        )
        lines.append("")

        for filepath in sorted(pragma_exclusions.keys()):
            entries = pragma_exclusions[filepath]
            short_path = filepath.replace(SOURCE_PREFIX, "")
            file_lines_count = sum(e["end_line"] - e["line"] + 1 for e in entries)
            lines.append(f"#### `{short_path}` ({file_lines_count} lines)")
            lines.append("")
            lines.append("| Lines | Type | Reason | Code |")
            lines.append("|-------|------|--------|------|")

            for entry in entries:
                if entry["end_line"] > entry["line"]:
                    line_ref = f"{entry['line']}-{entry['end_line']}"
                else:
                    line_ref = str(entry["line"])
                ptype = f"no {entry['pragma_type']}"
                reason = entry["reason"] if entry["reason"] else "*no reason given*"
                # Escape pipe characters in code for markdown table
                code = entry["code"].replace("|", "\\|")
                lines.append(f"| {line_ref} | {ptype} | {reason} | `{code}` |")

            lines.append("")
    else:
        lines.append("### Pragma Exclusions")
        lines.append("")
        lines.append("No `# pragma: no cover` or `# pragma: no branch` annotations found.")
        lines.append("")

    output = "\n".join(lines) + "\n"

    if stdout_mode:
        print(output, end="")
    else:
        Path("tests/TESTING_GAPS.md").write_text(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
