# Copyright (c) 2025 Preston Elder
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

"""Power Pet Door Python Library.

A Python library for communicating with Power Pet Door devices over the network.

Example usage:
    from powerpetdoor import PowerPetDoorClient

    client = PowerPetDoorClient(
        host="192.168.1.100",
        port=3000,
        keepalive=30.0,
        timeout=10.0,
        reconnect=5.0
    )
    client.start()
"""

from .client import (
    CommandError,
    PowerPetDoorClient,
    PrioritizedMessage,
    autoretract_from_door_options,
    build_set_hold_time_message,
    build_set_notifications_message,
    build_set_voltage_message,
    envelope_for_command,
    find_end,
    make_bool,
)
from .const import (
    CMD_CLOSE,
    CMD_DELETE_SCHEDULE,
    CMD_DISABLE_AUTO,
    CMD_DISABLE_AUTORETRACT,
    CMD_DISABLE_CMD_LOCKOUT,
    CMD_DISABLE_INSIDE,
    CMD_DISABLE_OUTSIDE,
    CMD_DISABLE_OUTSIDE_SENSOR_SAFETY_LOCK,
    CMD_ENABLE_AUTO,
    CMD_ENABLE_AUTORETRACT,
    CMD_ENABLE_CMD_LOCKOUT,
    CMD_ENABLE_INSIDE,
    CMD_ENABLE_OUTSIDE,
    CMD_ENABLE_OUTSIDE_SENSOR_SAFETY_LOCK,
    CMD_GET_DOOR_BATTERY,
    CMD_GET_DOOR_OPEN_STATS,
    CMD_GET_DOOR_STATUS,
    CMD_GET_HOLD_TIME,
    CMD_GET_HW_INFO,
    CMD_GET_NOTIFICATIONS,
    CMD_GET_POWER,
    CMD_GET_SCHEDULE,
    CMD_GET_SCHEDULE_LIST,
    CMD_GET_SENSOR_TRIGGER_VOLTAGE,
    CMD_GET_SENSORS,
    CMD_GET_SETTINGS,
    CMD_GET_SLEEP_SENSOR_TRIGGER_VOLTAGE,
    CMD_GET_TIME,
    CMD_GET_TIMERS_ENABLED,
    CMD_GET_TIMEZONE,
    CMD_HAS_REMOTE_ID,
    CMD_HAS_REMOTE_KEY,
    CMD_OPEN,
    CMD_OPEN_AND_HOLD,
    CMD_POWER_OFF,
    CMD_POWER_ON,
    CMD_SET_HOLD_TIME,
    CMD_SET_NOTIFICATIONS,
    CMD_SET_SCHEDULE,
    CMD_SET_SENSOR_TRIGGER_VOLTAGE,
    CMD_SET_SLEEP_SENSOR_TRIGGER_VOLTAGE,
    CMD_SET_TIMEZONE,
    COMMAND,
    COMMAND_ENVELOPE_COMMANDS,
    CONFIG,
    DOOR_OPTION_AUTORETRACT,
    DOOR_STATE_CLOSED,
    DOOR_STATE_CLOSING,
    DOOR_STATE_CLOSING_MID_OPEN,
    DOOR_STATE_CLOSING_TOP_OPEN,
    DOOR_STATE_HOLDING,
    DOOR_STATE_IDLE,
    DOOR_STATE_KEEPUP,
    DOOR_STATE_RISING,
    DOOR_STATE_SLOWING,
    DOOR_STATUS,
    DOOR_TO_PHONE,
    FIELD_AUTO,
    FIELD_AUTORETRACT,
    FIELD_CMD,
    FIELD_CMD_LOCKOUT,
    FIELD_DIRECTION,
    FIELD_DOOR_STATUS,
    FIELD_FW_MAJOR,
    FIELD_FW_MINOR,
    FIELD_FW_PATCH,
    FIELD_HAS_REMOTE_ID,
    FIELD_HAS_REMOTE_KEY,
    FIELD_HW_REVISION,
    FIELD_HW_VERSION,
    FIELD_INSIDE,
    FIELD_LOW_BATTERY_NOTIFICATIONS,
    FIELD_MSG_ID,
    FIELD_MSG_ID_RESPONSE,
    FIELD_OUTSIDE,
    FIELD_OUTSIDE_SENSOR_SAFETY_LOCK,
    FIELD_POWER,
    FIELD_REASON,
    FIELD_SENSOR_OFF_INDOOR_NOTIFICATIONS,
    FIELD_SENSOR_OFF_OUTDOOR_NOTIFICATIONS,
    FIELD_SENSOR_ON_INDOOR_NOTIFICATIONS,
    FIELD_SENSOR_ON_OUTDOOR_NOTIFICATIONS,
    FIELD_SETTINGS,
    FIELD_SUCCESS,
    FIELD_TIME,
    FIELD_TOTAL_AUTO_RETRACTS,
    FIELD_TOTAL_OPEN_CYCLES,
    FIELD_VOLTAGE,
    PHONE_TO_DOOR,
    PING,
    PONG,
    PRIORITY_CRITICAL,
    PRIORITY_HIGH,
    PRIORITY_LOW,
    PRIORITY_MEDIUM,
    TIME_FORMAT,
)
from .door import (
    BatteryInfo,
    DoorStatus,
    NotificationSettings,
    PowerPetDoor,
    Schedule,
    ScheduleTime,
)
from .schedule import (
    END_OF_DAY,
    MIDNIGHT,
    build_set_schedule_message,
    compress_schedule,
    compute_schedule_diff,
    normalise_window_end,
    schedule_entry_content_key,
    schedule_template,
    schedule_window_is_empty,
    validate_schedule_entry,
    week_0_mon_to_sun,
    week_0_sun_to_mon,
    window_minutes,
)
from .tz_utils import (
    async_init_timezone_cache,
    find_iana_for_posix,
    get_available_timezones,
    get_posix_tz_string,
    init_timezone_cache_sync,
    is_cache_initialized,
    parse_posix_tz_string,
)

__version__ = "0.5.0"
__all__ = [
    # Door facade
    "BatteryInfo",
    "DoorStatus",
    "NotificationSettings",
    "PowerPetDoor",
    "Schedule",
    "ScheduleTime",
    # Client
    "CommandError",
    "PowerPetDoorClient",
    "PrioritizedMessage",
    "autoretract_from_door_options",
    "build_set_hold_time_message",
    "build_set_notifications_message",
    "build_set_voltage_message",
    "envelope_for_command",
    "find_end",
    "make_bool",
    # Schedule utilities
    "END_OF_DAY",
    "MIDNIGHT",
    "build_set_schedule_message",
    "compress_schedule",
    "compute_schedule_diff",
    "normalise_window_end",
    "schedule_entry_content_key",
    "schedule_template",
    "schedule_window_is_empty",
    "validate_schedule_entry",
    "window_minutes",
    "week_0_mon_to_sun",
    "week_0_sun_to_mon",
    # Timezone utilities
    "async_init_timezone_cache",
    "find_iana_for_posix",
    "get_available_timezones",
    "get_posix_tz_string",
    "init_timezone_cache_sync",
    "is_cache_initialized",
    "parse_posix_tz_string",
    # Constants - Message types
    "COMMAND",
    "COMMAND_ENVELOPE_COMMANDS",
    "CONFIG",
    "DOOR_STATUS",
    "PING",
    "PONG",
    # Constants - Message envelope
    "DOOR_TO_PHONE",
    "FIELD_CMD",
    "FIELD_DIRECTION",
    "FIELD_MSG_ID",
    "FIELD_MSG_ID_RESPONSE",
    "FIELD_REASON",
    "PHONE_TO_DOOR",
    # Constants - Notification events
    "TIME_FORMAT",
    # Constants - Commands
    "CMD_CLOSE",
    "CMD_DELETE_SCHEDULE",
    "CMD_DISABLE_AUTO",
    "CMD_DISABLE_AUTORETRACT",
    "CMD_DISABLE_CMD_LOCKOUT",
    "CMD_DISABLE_INSIDE",
    "CMD_DISABLE_OUTSIDE",
    "CMD_DISABLE_OUTSIDE_SENSOR_SAFETY_LOCK",
    "CMD_ENABLE_AUTO",
    "CMD_ENABLE_AUTORETRACT",
    "CMD_ENABLE_CMD_LOCKOUT",
    "CMD_ENABLE_INSIDE",
    "CMD_ENABLE_OUTSIDE",
    "CMD_ENABLE_OUTSIDE_SENSOR_SAFETY_LOCK",
    "CMD_GET_DOOR_BATTERY",
    "CMD_GET_DOOR_OPEN_STATS",
    "CMD_GET_DOOR_STATUS",
    "CMD_GET_HOLD_TIME",
    "CMD_GET_HW_INFO",
    "CMD_GET_NOTIFICATIONS",
    "CMD_GET_POWER",
    "CMD_GET_TIMERS_ENABLED",
    "CMD_GET_SCHEDULE",
    "CMD_GET_SCHEDULE_LIST",
    "CMD_GET_SENSOR_TRIGGER_VOLTAGE",
    "CMD_GET_SENSORS",
    "CMD_GET_SLEEP_SENSOR_TRIGGER_VOLTAGE",
    "CMD_GET_SETTINGS",
    "CMD_GET_TIME",
    "CMD_GET_TIMEZONE",
    "CMD_HAS_REMOTE_ID",
    "CMD_HAS_REMOTE_KEY",
    "CMD_OPEN",
    "CMD_OPEN_AND_HOLD",
    "CMD_POWER_OFF",
    "CMD_POWER_ON",
    "CMD_SET_HOLD_TIME",
    "CMD_SET_NOTIFICATIONS",
    "CMD_SET_SCHEDULE",
    "CMD_SET_SENSOR_TRIGGER_VOLTAGE",
    "CMD_SET_SLEEP_SENSOR_TRIGGER_VOLTAGE",
    "CMD_SET_TIMEZONE",
    # Constants - Fields
    "FIELD_AUTO",
    "FIELD_AUTORETRACT",
    "FIELD_CMD_LOCKOUT",
    "FIELD_DOOR_STATUS",
    "FIELD_HAS_REMOTE_ID",
    "FIELD_HAS_REMOTE_KEY",
    "FIELD_VOLTAGE",
    "FIELD_INSIDE",
    "FIELD_LOW_BATTERY_NOTIFICATIONS",
    "FIELD_OUTSIDE",
    "FIELD_OUTSIDE_SENSOR_SAFETY_LOCK",
    "FIELD_POWER",
    "FIELD_SENSOR_OFF_INDOOR_NOTIFICATIONS",
    "FIELD_SENSOR_OFF_OUTDOOR_NOTIFICATIONS",
    "FIELD_SENSOR_ON_INDOOR_NOTIFICATIONS",
    "FIELD_SENSOR_ON_OUTDOOR_NOTIFICATIONS",
    "FIELD_SETTINGS",
    "FIELD_SUCCESS",
    "FIELD_TIME",
    "FIELD_TOTAL_AUTO_RETRACTS",
    "FIELD_TOTAL_OPEN_CYCLES",
    # Constants - Hardware/firmware version fields
    "FIELD_FW_MAJOR",
    "FIELD_FW_MINOR",
    "FIELD_FW_PATCH",
    "FIELD_HW_REVISION",
    "FIELD_HW_VERSION",
    # Constants - Door states
    "DOOR_OPTION_AUTORETRACT",
    "DOOR_STATE_CLOSED",
    "DOOR_STATE_CLOSING",
    "DOOR_STATE_CLOSING_MID_OPEN",
    "DOOR_STATE_CLOSING_TOP_OPEN",
    "DOOR_STATE_HOLDING",
    "DOOR_STATE_IDLE",
    "DOOR_STATE_KEEPUP",
    "DOOR_STATE_RISING",
    "DOOR_STATE_SLOWING",
    # Constants - Priorities
    "PRIORITY_CRITICAL",
    "PRIORITY_HIGH",
    "PRIORITY_LOW",
    "PRIORITY_MEDIUM",
]
